DELETE FROM NUMBERS;

INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 1, 25);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 2, 37);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 3, 48);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 4, 50);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 5, 7);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(1, 6, 6);

INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 1, 2);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 2, 7);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 3, 48);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 4, 5);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 5, 17);
INSERT INTO NUMBERS(DRAWNUMBER, INDEX, NUMBER) VALUES(2, 6, 6);
